"""Write docs/api/openapi.yaml from the running FastAPI app.

The spec is GENERATED, never hand-edited: the app is the source of truth, so a
hand-written copy can only ever be wrong or stale.

    python scripts/export_openapi.py            # rewrite docs/api/openapi.yaml
    python scripts/export_openapi.py --check    # exit 1 if routes have drifted

--check compares the set of (method, path) pairs, not the file bytes.
requirements.txt is unpinned, so FastAPI/pydantic can legitimately reshape
schema fragments between minor versions; a byte comparison would fail CI for
reasons that are not documentation drift. A route added, removed or renamed is
exactly what makes the committed spec stale, and that is what is compared.
"""
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "docs" / "api" / "openapi.yaml"
HEADER = (
    "# GENERATED by scripts/export_openapi.py from the FastAPI app. Do not edit.\n"
    "# Regenerate: python scripts/export_openapi.py\n"
)
_METHODS = {"get", "post", "put", "patch", "delete", "head", "options"}


def build_spec() -> dict:
    sys.path.insert(0, str(ROOT))
    from app.main import app
    return app.openapi()


def routes(spec: dict) -> set:
    return {(m.upper(), p) for p, item in spec.get("paths", {}).items()
            for m in item if m in _METHODS}


def render(spec: dict) -> str:
    return HEADER + yaml.safe_dump(spec, sort_keys=False, allow_unicode=True,
                                   default_flow_style=False, width=100)


def drift(committed_path: Path = OUT) -> tuple:
    """(missing_from_doc, extra_in_doc) as sorted lists of (METHOD, path)."""
    live = routes(build_spec())
    committed = routes(yaml.safe_load(committed_path.read_text(encoding="utf-8")) or {})
    return sorted(live - committed), sorted(committed - live)


def main(argv: list) -> int:
    if "--check" in argv:
        missing, extra = drift()
        for m, p in missing:
            print(f"in app but not in docs/api/openapi.yaml: {m} {p}")
        for m, p in extra:
            print(f"in docs/api/openapi.yaml but not in app: {m} {p}")
        return 1 if (missing or extra) else 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    spec = build_spec()
    OUT.write_text(render(spec), encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}: {len(routes(spec))} operations, "
          f"{len(spec.get('components', {}).get('schemas', {}))} schemas")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
